Added Higor name to table
Professor-Dudarts/ludus_service_standings pull request #13
Opened 2023-03-06 15:46 UTC by higorbuueno

2023-03-06 16:51 UTC, nibiroo approved these changes
Approved review

2023-03-06 17:01 UTC, nibiroo requested changes
Refazer alteração, pois, terá conflito com a [PR que foi mergiada do Ruben](https://github.com/Professor-Dudarts/ludus_service_standings/commit/ff66bd000cdcde1e2cc0355967202d605f12f5e0)

2023-03-06 17:30 UTC, PPedrosouza commented
> Refazer alteração, pois, terá conflito com a [PR que foi mergiada do Ruben](https://github.com/Professor-Dudarts/ludus_service_standings/commit/ff66bd000cdcde1e2cc0355967202d605f12f5e0)

De acordo com a review acima.

2023-03-06 17:52 UTC, PPedrosouza requested changes
Refazer as alterações por conta do conflito do PR do dev_Ruben

2023-03-07 00:34 UTC, higorbuueno commented
Solucionei os conflitos, poderiam ver agora?

2023-03-07 00:41 UTC, nibiroo approved these changes

2023-03-07 00:44 UTC, PPedrosouza approved these changes
Approved

2023-03-07 00:44 UTC, nibiroo approved these changes

2023-03-07 00:44 UTC, merged