[standings-41] - Mapeando entidade campeonatos em NestJS com Controlador, Modulo, Entidade e Rotas.
Professor-Dudarts/ludus_service_standings pull request #43
Opened 2023-04-01 01:58 UTC by nibiroo

2023-04-01 04:22 UTC, higorbuueno requested changes

2023-04-01 04:22 UTC, higorbuueno commented on backend-service/src/campeonato/campeonato.controller.ts
> +  @Patch(':id')
Nós vamos utilizar put, e atualizar o objeto por completo, creio que fica uma maneira mais fácil para trabalhar.
Claro que há casos que vamos utilizar um DTO personalizado, mas como estamos fazendo um microserviço no escuro vamos trabalhar sempre com o objeto inteiro.

2023-04-01 04:22 UTC, higorbuueno commented on backend-service/src/campeonato/campeonato.module.ts
> +})
Ainda não utilizamos, mas talvez num futuro breve será necessário.
Nós termos um "exports: [CampeonatoService]", pois caso outro serviço precisar utilizá-lo, já estará para uso "publico".

2023-04-01 04:22 UTC, higorbuueno commented on backend-service/src/campeonato/dto/update-campeonato.dto.ts
> +export class UpdateCampeonatoDto extends PartialType(CreateCampeonatoDto) {
Talvez esse DTO não vai ser necessário, pode apagar, se necessário, implementamos depois, visto que não vamos utilizar o PATCH e sim o PUT, então vamos sempre passar o objeto completo, como é feito na hora do cadastro.

2023-04-01 04:22 UTC, higorbuueno commented on backend-service/src/campeonato/entities/campeonato.entity.ts
> +export class Campeonato {
Beleza, como só criou o arquivo da Entity está ok, não temos a lib TypeORM instalada ainda, então está ok.
Quando fizermos a config da conexão com o banco este cara mudar.

2023-04-03 18:53 UTC, higorbuueno approved these changes

2023-04-04 14:33 UTC, rubenhanderson approved these changes

2023-04-06 01:19 UTC, PPedrosouza commented
Aprovado!

2023-04-06 01:20 UTC, PPedrosouza approved these changes

2023-04-06 01:20 UTC, merged